### ISSUE TITLE
[BUG] Crash when selecting .bin dump file for the first time

### ISSUE THREAD

**Issue by DarrenHSKG** [placiibo/placiibo-bugs#10]
**Describe the bug**
When I select the key (key-retail.bin) then select an amiibo .bin, it crashes ONLY on the first install.

**To Reproduce**
1. Go to the app when you first install it on an iPhone 8 running iOS 13.4.1
2. Click on the key-retail bin file
3. Scroll down to select the amiibo bin file
4. See error (crash)

**Expected behaviour**
Not to crash, to be able to press write tag and write the amiibo

**Actual behaviour**
Crash the app, to fix simply restart.

**Reproducibility :** 
I have no idea, I only did it once.

**iOS version**: 13.4.1
**iOS device**: iPhone 8 (not +)
**Jailbroken**: No
**placiibo version + build**: 0.1.0 (12.1.1)
**Screenshots**
None :(
**Screen recording**
Wasn't recording and only got it once.
**Relevant files**
key-retail.bin that I got from amiibo dump 4.0 and [AC] 305 - Celeste.bin (same source)

**NFC Tag**
None: I didn't scan anything
**Additional context**
Seems like it's a problem with the cache or something

**Comment by wabawuby** [comment]
I’ve been having the same problem. I had the key-retail bin file loaded in the same field as the character’s bin file. When I tried to select the bin file(s), the app immediately crashed. Tried putting key-retail bin file as encryption key. The app crashed as well. I tried writing on one card but the app crashed and no progress bar was shown (I bet the tag was dead). I miss the old version 😢

**Comment by placiibo** [comment]
Could you confirm this still happens with a fresh install of the current version 0.2.0 (18) by deleting the app and reinstalling it along with importing the files that caused issues?

**Comment by placiibo** [comment]
Issue should be resolved in the most current version, no follow up has occured by the original reporter. 

Marked as resolved and closed. Please open a new bugreport if this issue reoccurs in 0.2.0 (403) or newer.

**Comment by DarrenHSKG** [comment]
Can confirm it does not happen again in the latest version. Bug resolved, hopefully doesn't happen again.
