### ISSUE TITLE
[Feature] Support for Powertag and N2elite

### ISSUE THREAD

**Issue by chrisw491** [placiibo/placiibo-bugs#12]
**Try to describe your suggestion succinctly in the form of a user story**
As a power tag user, I want official support for rewritable tags such as power tag and N2elite

**Is your feature request related to a problem? Please describe.**
Whenever I write to my power tag using placiibo, my Nintendo switch won’t recognize it as an amiibo, but when I use an NFC reader it shows the amiibo file on the powertag. 

**Describe the solution you'd like**
Official support for rewriting power tags and n2elite tags.

**Comment by placiibo** [comment]
I'm not sure if official support is possible. but it's certainly something interesting to look into.

**Comment by chrisw491** [comment]
Thank you so much!
