### ISSUE TITLE
[BUG] "Placiibo" Header Overlap 

### ISSUE THREAD

**Issue by Semrix** [placiibo/placiibo-bugs#14]
**Describe the bug**
Placiibo header glitched into the first bin file and was no longer accessible until I force closed the app. 
**To Reproduce**
1.Select bin file
2.Write to tag
3.Error Occurs

**Expected behaviour**
The header to not glitch into the bin files.

**Actual behaviour**
Header glitched into the first bin file.

**Reproducibility :** 
Only occurred once after writing 4 tags, and tried to reproduce it but it didn't occur.

**iOS version**:
13.4.1
**iOS device**: 
iPhone XR
**Jailbroken**: 
No
**placiibo version + build**: 
Version 0.1.0 (12.2.1)

**Screenshots**
https://imgur.com/a/3NEWENH

**Relevant files**
Happened after writing a coco.bin or fang.bin

**Additional context**
Occurred after writing a fang.bin or coco.bin and the tag still worked fine. The app was still fine after force closing it. Wrote another tag, no error occurs.

**Comment by placiibo** [comment]
Closed, not relevant for current version due to UI redesign.
