### ISSUE TITLE
[BUG] Hit target for bin list doesn’t fill table cell

### ISSUE THREAD

**Issue by someToast** [placiibo/placiibo-bugs#16]
**Describe the bug**
Tapping a cell in the table of loaded bins doesn’t select the item unless you tap on the name of the bin itself.

**To Reproduce**
1. Tap the cell of a given bin anywhere to the right of the bin name.

**Expected behaviour**
For the bin in that cell to be selected.

**Actual behaviour**
No operation.

**Reproducibility :** 
100% reproducible.

**iOS version**:
13.5 (17F75)

**iOS device**: 
iPhone 11 Pro

**Jailbroken**: 
No

**placiibo version + build**: 
v.0.1.0 

**Screenshots**
N/A

**Screen recording**
N/A

**Relevant files**
N/A

**NFC Tag**
N/A

**Additional context**
I’m sure this is a known issue. Just getting it in the tracker.

**Comment by Minibyte** [comment]
Just wanted to add a +1 to this occurring on iOS 13.4.1 (iPhone 11 Pro) as well. Placiibo ver. 0.1.0.

Also reproducible in any cell of the "About" section as well. The target area is only just larger than the text.

**Comment by someToast** [comment]
TestFlight’s telling me I have no apps available to test.

**Comment by placiibo** [comment]
About a month ago the original TestFlight ended and a new one with a new pool of people started. There was a sign up period. So it probably means you didn't sign up back then. There will be some info on getting placed in the current TestFlight this weekend.

**Comment by placiibo** [comment]
The current version –build 403 of 0.2.0– should not have this issue in the 
'About' section of the app. 
The issue still exists in the binary library, sadly this is a SwiftUI bug and currently there's no graceful workaround available. Between that and the report going stale, I'm closing this bug. 

Please file a new report if this issue reoccurs in the 'About' section or elsewhere besides the binary libary. 

As an aside, there's now an option to join the current TestFlight program if you still have the old version on your phone: https://redd.it/hknbpf
