### ISSUE TITLE
The app will not open

### ISSUE THREAD

**Issue by alicat6288** [placiibo/placiibo-bugs#17]
I’ve had a really rough experience with this app so far. If you can help me in any way with the problem I have been having, please do. Thank you. (I have an iPhone XR)
The app was ok in the beginning. I tried putting all of the files in, but it just wouldn’t allow me to press the button to scan my tag. It even highlighted to a different color when I pressed the file. I undownloaded and redownloaded the app a couple times, but this didn’t work. I figured I’d wait a day or two to see what would happen. Currently, the app will not open. I just have a black screen and then it goes to my phone’s home screen after about ten seconds. It then displays a notification that the app has crashed. This has happened every time I have tried to open the app even after reinstalling it. I’ve even tried resetting my phone, but this still hasn’t helped. Please tell me what I can do to fix this problem.

**Comment by placiibo** [comment]
Please confirm if you still have this issue with the latest version that was pushed out this week. If so please create a new bug report by filling out the template here: https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md&title=%5BBUG%5D
