### ISSUE TITLE
[Feature] Tag writing timeout notification

### ISSUE THREAD

**Issue by Marek242** [placiibo/placiibo-bugs#18]
**Try to describe your suggestion succinctly in the form of a user story**
As a user, I want a warning that an attempt to write to a tag timed out so that it is more clear when you have not placed the tag in the correct location on the phone.

**Is your feature request related to a problem? Please describe.**
Once you have written to a tag successfully, it is clear that it has happened. However, placement of the tag on the phone can be confusing, and the image shown isn't entirely accurate as to the correct location. A new user is not given any notification of a failed attempt to write; it just stops without a warning alert.

**Describe the solution you'd like**
If an attempt is made to write to a tag but it does not occur, some kind of warning/alert should pop up. Either a "no tag detected" or "timed out" or "please move tag and try again" or some similar warning would be useful.

**Describe alternatives you've considered**
Alternately, the graphic when the phone is searching for the tag could have some text about how a progress bar and check mark will appear if the attempt is successful.

**Additional context**
An additional graphic about tag placement on the phone could assist new users.

**Comment by placiibo** [comment]
As I've explained in #15 there's no great way of providing a useful graphic sadly. As for an indicator when it timed out, it automaticaly times out after 60 seconds and will show an error message (circle with cross) if that happens.
