### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by EricEttes** [placiibo/placiibo-bugs#2]
I’ve used Placiibo successfully to make a backup of my Amiibo’s. Here’s a few findings/ideas for the app:

Bug/UI glitch: While writing a few tags I scrolled up and down a bit and the Placiibo text floated on top of the first item in the list (I was unable to click that item during this). Closing/reopening the app fixed it for me, but now I’m unable to reproduce this (thought I’d tell you anyway, maybe more people have the same issue).

Idea: Add an indicator when a bin file hasn’t been written yet (or an indicator that shows the number of writes)

So far, 100% of the tags I wrote work. Thanks!

I used:
iPhone 11 Pro Max
iOS 13.4
Placiibo Version 0.1.0

**Comment by placiibo** [comment]
Thank you for the feedback. 

Could you use the [Bug report](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md&title=%5BBUG%5D) or [Feature request](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=feature&template=feature_request.md&title=%5BFeature%5D)  templates respectively to submit them into the issue tracker? 

Thank you

**Comment by EricEttes** [comment]
Done! See Bug #7 and #9, and Feature #8

**Comment by placiibo** [comment]
Thanks, much appreciated!
