### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kirbKiller87** [placiibo/placiibo-bugs#20]
Updated my iPhone XS Max to iOS 13.5.1 and updated the app to 0.1.0(265A) this morning 10Jun. I like the new UI but hate how when it updated it deleted all the files I had saved. I went to write a tag and the app immediately crashed. This crash happened 4 times for me always immediately after attempting to write a tag.

**Comment by placiibo** [comment]
Please see comment over at #21
