### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kirbKiller87** [placiibo/placiibo-bugs#21]
After the new update to 0.1.0(319) for iOS, I reported a bug issue I’ve been experiencing heavily with my iPhone XS Max writing tags. The app opens fine. I’m able to load a key bin file fine. The issue that is becoming a real headache for me is selecting a bin file to write and the app crashes immediately upon selecting the bin file to write.

**Comment by placiibo** [comment]
Could you please file a new bug report by using the template and attach the two files involved?
