### ISSUE TITLE
[Feature request] Optional enc file, bin name

### ISSUE THREAD

**Issue by HQuest** [placiibo/placiibo-bugs#22]
Hi there. I’m the dude who found the empty write bug earlier today (yesterday?) on Reddit.

Anyhow, over my feedback report you stated “Encryption is optional”, however currently after you add an encryption file, you have no way to remove a key (temp or perm). Therefore it ain’t optional :) I would think a button to remove current enc key from the encryption pane should do most of the trick, and as you are planning on “quick write” and a “pro write” modes, you obey the enc key existence on the quick mode, and you have a toggle to use or not a companion enc key on the pro mode. That would make the enc key fully optional in both ways. The remarks when an enc key is or isn’t found during write are great.

Also, regarding the lack of a name for the loaded bin file. I understand you are taking the file name if a name is not entered, but it would help if the file name was displayed anywhere so the end user knows a file was selected (and which file was selected). Maybe you should just populate the name field with the file name - quick and dirty but gets the job done. Might sound obvious for me and you but average users will come asking “I picked a file and it does not do anything” because there is no feedback a file was selected, only a panel closed and back to the emptiness it was before. Been there, they did that!

Also, when you add a bin (process only able to be performed after a write mode selection), the page goes back to the write mode selection instead of the write mode you were already in. Minor time saving.

Last but not least, sad you took away the ability for files to be managed via the Files app. But I understand some of the reasons why.

**Comment by placiibo** [comment]
Thanks for your feedback, some of the stuff you mentioned has been added/fixed in the latest version, please check that one out. 

It would be very helpful if you'd fill out [this template](https://github.com/placiibo/placiibo-bugs/issues/new?assignees=&labels=feature&template=feature_request.md&title=%5BFeature%5D) for any future suggestions you might still have.
