### ISSUE TITLE
[BUG] App crashes after attempting to write

### ISSUE THREAD

**Issue by laviedeceline31** [placiibo/placiibo-bugs#23]
The app crashes right after I add the bin file and attempt to write. 

Reproduce:
1. I added the key bin file to the encryption key point.
2. I go to write and add the same key bin file to prepare to write.
3. I click on the key bin file on the write page.
4. App immediately crashes upon clicking on the file.

Expected behavior:
Upon clicking the key bin file on the write page the "write to tag" button should be available to tap and proceed to write to the tag.

Actual behavior:
The app crashes upon clicking on the key bin file therefore not allowing me to proceed to write to tag. Even upon restarting the app several times, it still crashes at that last step. 

Reproducibility:
The app crashed every time I tried to reattempt to write a tag. The bug is consistent with every attempt. 

![IMG_9754](https://user-images.githubusercontent.com/65487664/84358021-5eeae180-ab7b-11ea-9f91-cccbb725288d.jpg)

https://www.reddit.com/user/laviedeceline31/comments/h0uknj/placiibo_bug/?utm_source=share&utm_medium=web2x

**Comment by placiibo** [comment]
I can’t reproduce this bug with the same bin file. Could you provide the files involved? Both the key binary you’re using and the binary you’re trying to write?

**Comment by laviedeceline31** [comment]
It won't let me upload the individual files so I attached the whole zip file. The key binary is labeled as "key_retail.bin" and the binary I am trying to write is "[AC] 253 - Genji.bin"

[Amiibo Bin Dump_V4_.zip](https://github.com/placiibo/placiibo-bugs/files/4769048/Amiibo.Bin.Dump_V4_.zip)

**Comment by placiibo** [comment]
That’s odd, I can’t reproduce it with those. I’ll have to do some more research, I think I find the crash logs so guess I’ll have to set up a date with them. 

In the meantime as I work on this, try deleting the app and re-importing the files in question. It might be something got corrupted, else I’ll have to see if I can get my hands on an Xr to see if that’s a determining factor.

**Comment by placiibo** [comment]
Could you also fill in these questions from the bug report template so I can better catalogue the issue and include any crash logs you have under Settings > Privacy > Analytics & Improvement > Analytics Data

**iOS version**:
Version of iOS this bug occurred on (can be found in Settings.app > General)
**iOS device**: 
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: 
Whether or not your device is jailbroken
**If jailbroken, can you reproduce the issue when you remove the jailbreak?**:
If you can reproduce it, if applicable, please include both crashlogs find under the Privacy settings from before and after removing the jailbreak. 
**How did you remove the jailbreak?**:
Did you reset on the phone itself through Settings > General > Reset or did you restore iOS through iTunes/Finder?

**Comment by placiibo** [comment]
Issue should be resolved in the most current version, no follow up has occured by the original reporter.

Marked as resolved and closed. Please open a new bugreport if this issue reoccurs in 0.2.0 (403) or newer.
