### ISSUE TITLE
[BUG] List jumps up when selecting a binary below initial view

### ISSUE THREAD

**Issue by DistortionR** [placiibo/placiibo-bugs#24]
**Describe the bug**
I’m not sure if bug or intended but when a bin file is selected to write the list of files defaults to the top before the file is written. This means that when writing, if the file is far down the list, it’s impossible to double checking we have the right one selected. 

**To Reproduce**
1. Select bin file from list of files already added to the app (must be further down than the visible ones, I.e. you need to have to scroll to get to it 

**Expected behaviour**
I would expect it to keep the list where it is whilst writing to ensure the correct file is selected or to have the name of the file on the writing notice

**Actual behaviour**
As soon a the bin file is selected the list rolls all the way to the top even before writing the file

**Reproducibility :** 
Every time

**iOS version**:
13.5.1
**iOS device**: 
iPhone 11 Pro Max
**Jailbroken**
**placiibo version + build**: 
0.1.0(396)

**Screenshots**
If possible, add screenshots to help explain your problem.

**Screen recording**
If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**Relevant log files**
If applicable, please include the relevant crash log. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it. 

**NFC Tag**
If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred. 

**Additional context**

**Comment by placiibo** [comment]
Interesting, I'll have to see if I can reproduce that. Could you in the meantime provide a screenrecording of the occurance?

**Comment by DistortionR** [comment]
I’ve put the screen recording here as it don’t let me add to the comment directly https://youtu.be/0Vs8F3MjJUE

**Comment by placiibo** [comment]
Thank you for the recording, I'll look into it
