### ISSUE TITLE
[BUG]right files but still won’t work?

### ISSUE THREAD

**Issue by scarlett81** [placiibo/placiibo-bugs#25]
**Describe the bug**
A clear and concise description of what the bug is. i have downloaded the right files but whenever i try to put a character on a card, the app crashes.

**To Reproduce**
1. Go to settings, then encription key
2. upload “key_retail.bin”
3. Go back to NFC, press write, press pro, pick the character you want 

**Expected behaviour**
i expected the character to transfer onto the card 

**Actual behaviour**
What actually happened instead
the app crashed before i could do anything
**Reproducibility :** 
How consistent can you reproduce the issue?
it happens every time 

**iOS version**:
Version of iOS this bug occurred on (can be found in Settings.app > General)
**iOS device**: 13.5.1
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: iphone 8
Whether or not your device is jailbroken
**If jailbroken, can you reproduce the issue when you remove the jailbreak?**: i do not know what this means oops
If you can reproduce it, if applicable, please include both crashlogs find under the Privacy settings from before and after removing the jailbreak.  
**How did you remove the jailbreak?**:
Did you reset on the phone itself through Settings > General > Reset or did you restore iOS through iTunes/Finder?

**placiibo version + build**: 
Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. *Version 0.1.0 (10)* 
0.2.0 (18)

**Screenshots**
If possible, add screenshots to help explain your problem.
![D2801DF7-1658-4FEC-B38B-0D16B8AFE3B5](https://user-images.githubusercontent.com/67397353/85637872-38c44780-b639-11ea-88dd-afae0afca154.png)
![C19EB129-CECB-4B04-B9A2-26C58D6B813B](https://user-images.githubusercontent.com/67397353/85637876-39f57480-b639-11ea-81f9-62a1a63ef4ad.png)

**Screen recording**
If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**Relevant log files**
If applicable, please include the relevant crash log. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it. 

**NFC Tag**
If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred. 

**Additional context**

**Comment by placiibo** [comment]
Thanks for filing a bug report. I'm having trouble replicating the bug. Could you attach the files you've used to the report and the crash report? The instructions on how to find the crash report are described in the template. 

Thanks again!

**Comment by scarlett81** [comment]
hi! when you say files do you mean the stuff i used to upload the
characters before it shut down?

**Comment by placiibo** [comment]
Yes the files you’ve loaded into the app including the key file. 

And any crash logs you have. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it.

**Comment by placiibo** [comment]
Thanks for sending me the files. I have replicated your setup (used the exact same files in the same order and key file) but haven’t been able to cause a crash

I’ll do some more research once I’ve received a crash log, I’m hoping it’ll be able to tell me what is causing it

![CAD180EA-7E08-472B-AB95-B7C6DC10BBBA.png](https://app.gitkraken.com/api/glo/boards/5ec02a117a583d001136d16a/attachments/5ef429c242d4300011113e77)

**Comment by scarlett81** [comment]
it crashes whenever i try to make the characters name turn blue if that
helps!

**Comment by placiibo** [comment]
Please see if you still encounted this issue with the new update.

**Comment by ohmygilly** [comment]
I have the same problem

**Comment by ohmygilly** [comment]
![2FBD486D-808B-42C9-A44E-F14DADE14166](https://user-images.githubusercontent.com/67455282/85905935-71ce0900-b83f-11ea-91f3-560f170cf635.png)

![2F32758F-00D5-4742-B296-6AF8F62A2744](https://user-images.githubusercontent.com/67455282/85905956-814d5200-b83f-11ea-9450-7f5f2b8d6b20.png)

**Comment by placiibo** [comment]
Cleaned up comments that were unrelated to this bug

**Comment by placiibo** [comment]
Issue should be resolved in the most current version, no follow up has occured by the original reporter.

Marked as resolved and closed. Please open a new bugreport if this issue reoccurs in 0.2.0 (403) or newer.
