### ISSUE TITLE
[BUG] Loading new encryption key does not 'take' until restarting app

### ISSUE THREAD

**Issue by bezoarboy** [placiibo/placiibo-bugs#26]
**Describe the bug**

If an encryption key is already loaded, loading a new key does not result in the new key being used until the app is restarted.

**To Reproduce**

1. Load an **initial** encryption key. It will say "Encryption key ABC.bin is loaded"
2. Exit settings and then select Encryption Key again. (Possibly, might need to restart app after exiting settings.)
3. Click Load encryption key and select a **new** key "XYZ.bin". It will say "Encryption key XYZ.bin is loaded"
4. Go back to NFC and then go back to Settings --> Encryption Key
5. It's back to "Encryption key ABC.bin is loaded"!!!
6. If you attempt to write a tag at this point, ABC.bin is used, and NOT XYZ.bin (but unfortunately, there is no display on the Write: Pro screen that specifies which "Encryption key loaded.", so I lost a few tags before figuring this out :(
7. Force quit the app and open it again. Go to Settings -> Encryption Key
8. At this point, you'll see that: "Encryption key XYZ.bin is loaded."
9. Writing a tag at this point DOES use the XYZ.bin key.

**Expected behaviour**

After loading a new encryption key, the old key should not come back, and the new one will be used, even without restarting the app.

Could also consider adding to the "Write: Pro" screen specifying WHICH key is loaded, rather than just "Encryption key loaded", to reduce the possiblity of using the wrong encryption key.

**Actual behaviour**

After loading a new encryption key, the old one was used until I restarted the app.

**Reproducibility :** 

All steps have been reproducible, but I have not (intentionally) reproduced more than once the step 6 above, where I actually wrote a new tag and found it to be (presumably) using the old key (because the tag didn't work).

**iOS version**: 13.5.1

**iOS device**:  iPhone 11 Pro

**Jailbroken**:  No

**placiibo version + build**: 0.2.0 (18)

**Screenshots** (none available, can obtain if wanted)

**Screen recording** (none available)

**Relevant files** (presumably not permissible to upload particular key bin files)

**Relevant log files** (not relevant -- no crash occurred)

**NFC Tag** (not available)

**Additional context** (none)

**Comment by placiibo** [comment]
Thanks for the report. I’ve confirmed this bug, it should be fixed with the next update. 

Just as a reassurance: the issue lies with the fact that the Encryption key screen doesn’t properly read the stored name of the imported file (the app does read it properly at start which is why that makes a difference), however the actual key file used during write is stored separately so it will always use what you’ve last imported regardless of what the text says.
