### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by florecitu** [placiibo/placiibo-bugs#27]
"+" button to add bin files to write a card is not very tactile responsive.
When tapping +, it takes many taps to make it work. It's not very responsive. At the first tap, it should take you to your iCloud folder. This has happened every time I've used the app (5 times so far).

Running on iOS 13.5.1, on iPhone 11, not jailbroken.

Placiibo 0.2.0 (18)

**Comment by placiibo** [comment]
Sadly this is due to a bug in Swift that causes the hit area to jump around sometimes. I've implemented a workaround that should reduce this issue. Be sure to update through TestFlight and test it out.
