### ISSUE TITLE
[BUG] the app crashes when i write something 

### ISSUE THREAD

**Issue by ohmygilly** [placiibo/placiibo-bugs#28]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Actual behaviour**
What actually happened instead

**Reproducibility :** 
How consistent can you reproduce the issue?

**iOS version**:
Version of iOS this bug occurred on (can be found in Settings.app > General)
**iOS device**: 
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: 
Whether or not your device is jailbroken
**If jailbroken, can you reproduce the issue when you remove the jailbreak?**:
If you can reproduce it, if applicable, please include both crashlogs find under the Privacy settings from before and after removing the jailbreak. 
**How did you remove the jailbreak?**:
Did you reset on the phone itself through Settings > General > Reset or did you restore iOS through iTunes/Finder?

**placiibo version + build**: 
Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. *Version 0.1.0 (10)* 

**Screenshots**
If possible, add screenshots to help explain your problem.

**Screen recording**
If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**Relevant log files**
If applicable, please include the relevant crash log. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it. 

**NFC Tag**
If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred. 

**Additional context**

**Comment by placiibo** [comment]
Please file a new bug report and provide the information asked in the template.

**Comment by ohmygilly** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behaviour**
> A clear and concise description of what you expected to happen.
> 
> **Actual behaviour**
> What actually happened instead
> 
> **Reproducibility :**
> How consistent can you reproduce the issue?
> 
> **iOS version**:
> Version of iOS this bug occurred on (can be found in Settings.app > General)
> **iOS device**:
> For example iPhone XS, iPhone 7, etc.
> **Jailbroken**:
> Whether or not your device is jailbroken
> **If jailbroken, can you reproduce the issue when you remove the jailbreak?**:
> If you can reproduce it, if applicable, please include both crashlogs find under the Privacy settings from before and after removing the jailbreak.
> **How did you remove the jailbreak?**:
> Did you reset on the phone itself through Settings > General > Reset or did you restore iOS through iTunes/Finder?
> 
> **placiibo version + build**:
> Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. _Version 0.1.0 (10)_
> 
> **Screenshots**
> If possible, add screenshots to help explain your problem.
> 
> **Screen recording**
> If possible, add a screen recording to help explain your problem.You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.
> 
> **Relevant files**
> If applicable, add the bin files that you used while the bug occurred
> 
> **Relevant log files**
> If applicable, please include the relevant crash log. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it.
> 
> **NFC Tag**
> If applicable, please include a screenshot from the [TagInfo app by NXP](https://apps.apple.com/us/app/nfc-taginfo-by-nxp/id1246143596) of the NFC tag that was used when the bug occurred.
> 
> **Additional context**
> Add any other context about the problem here.

![E5747A80-A1B8-407D-9953-9286CFC78147](https://user-images.githubusercontent.com/67455282/85908757-01c48080-b849-11ea-97d3-0275889c7da5.png)
![296368C8-3402-4D3D-BF8C-B09E5BE53999](https://user-images.githubusercontent.com/67455282/85908761-0721cb00-b849-11ea-9823-5c9387fad324.png)

**Comment by placiibo** [comment]
@ohmygilly That's no a bug, but intended behaviour. What you're trying to import as key file doesn't seem to be a key file.  

Please (re)watch this video for a step by step walkthrough: https://www.youtube.com/watch?v=NFLKK1XT6x8

**Comment by ohmygilly** [comment]
Thank you for your reply i will watch the video again if there’s something
wrong i’ll let you know.
