### ISSUE TITLE
[BUG]Dark Mode Always On

### ISSUE THREAD

**Issue by fluffernauts** [placiibo/placiibo-bugs#29]
I have watched your YouTube video and followed your steps exactly. The app was already in dark mode when I downloaded. I tried changing to light mode but it did not turn the screen white as you said it would. The other setting of changing the app’s icon does work. 

**To Reproduce**
1. Go to settings
2. Click on Always Dark Mode
3. See error

The app is supposed to invert colors. 
**Actual behaviour**
What actually happened instead is nothing changed 

**Reproducibility :** 
How consistent can you reproduce the issue? 100% of the time. It has not changed since I first downloaded the app

**iOS version**: iOS 13.5.1
Version of iOS this bug occurred on (can be found in Settings.app > General)
**iOS device**: iPhone XS Max 
For example iPhone XS, iPhone 7, etc.
**Jailbroken**: Not jailbroken 
Whether or not your device is jailbroken
**If jailbroken, can you reproduce the issue when you remove the jailbreak?**:
If you can reproduce it, if applicable, please include both crashlogs find under the Privacy settings from before and after removing the jailbreak. 
**How did you remove the jailbreak?**:
Did you reset on the phone itself through Settings > General > Reset or did you restore iOS through iTunes/Finder?

**placiibo version + build**: 0.2.9
![6654F88C-0488-4664-B32A-385B0AF408AC](https://user-images.githubusercontent.com/66731747/85915913-8a2b2d00-b819-11ea-8951-9b6a9f853762.png)

Version of placiibo this bug occurred on (can be found at the top on the About screen and in Testflight). Build is the number between parenthesis. e.g. *Version 0.1.0 (10)* 

**Relevant files**
If applicable, add the bin files that you used while the bug occurred

**Relevant log files**
If applicable, please include the relevant crash log. You can find these in Settings > Privacy > Analytics & Improvement > Analytics Data. Look for placiibo and tap the share button in the upper right to export it. 

**NFC Ta

**Comment by placiibo** [comment]
What was the time of day when this happened? Or rather: was your phone set to dark mode?

The app respects the system settings for dark mode by default. The toggle doesn’t invert related to the system wide setting, it forces dark mode. I.e. It’s either what the phone is set to or dark mode.

**Comment by placiibo** [comment]
No follow up occured by original reporter, most likely user error. 

Closed bug report. Please open a new one if you encounter this issue in the lastest version.
