### ISSUE TITLE
[Feature] add multiple files in one go

### ISSUE THREAD

**Issue by ObiGKenobi** [placiibo/placiibo-bugs#3]
I would like to be able to select multiple bin files to import as it is frustrating when returned to the main screen after only selecting one file.

If this is not possible, is it possible to remain on the import screen and see a message saying "imported" or something and the icon on the import selection screen change to reflect it's imported status?

**Comment by placiibo** [comment]
Please fill out the Feature request template to submit a Feature request.

**Comment by placiibo** [comment]
Closed due to lack of follow up/lack of relevance for current version
