### ISSUE TITLE
[BUG] Importing a .bin but not saving it prevents re-import (break of sequence)

### ISSUE THREAD

**Issue by jgeorge44** [placiibo/placiibo-bugs#31]
Under Write, select + to import a bin file. Doesn’t matter what one. Select it and it’ll show the name in the next screen where you can click “Save” to save it. Don’t hit save, hit cancel. The bin isn’t imported, but if you go to re-import the same file the app says the file is already imported but it’s not selectable anywhere. 

This is with 0.2.0(100)

**Comment by jgeorge44** [comment]
The “Save” step seems redundant anyway really. If it’s a valid importable .bin file that hasn’t been imported already, i think it should just automatically be saved since any mistaken imports can be easily deleted by swiping the file off the imported list.

**Comment by placiibo** [comment]
Thanks, that a good find. I'll see if I can get it in the next build. 

As for the suggestion to ommit the save button; I'm not entirely sure if it'll fit the workflow I've got in mind for the future, plus it might mess with people who intended to give the binary a custom name, but I'll keep it in mind!

**Comment by placiibo** [comment]
Duplicate report found here: https://redd.it/hi2ls7

**Comment by placiibo** [comment]
Should be resolved in build 403, please delete the app and install 0.2.0 (403) from TestFlight to confirm that it's resolved.

**Comment by jgeorge44** [comment]
Verified fixed 0.2.0 (403) thank you!

**Comment by placiibo** [comment]
Thank you for confirming!
