### ISSUE TITLE
[BUG]"This key file is currently not supported"

### ISSUE THREAD

**Issue by iagokpedrosa** [placiibo/placiibo-bugs#33]
**Describe the bug**
Whenever I try to load a .bin file as encryption key the ap pops up a message saying "This key file is currently not supported".

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Encryption Key'
3. Click on 'Load encryption key'
4. Select any .bin file
5. See error.

**Expected behaviour**
The app should indicate that the encryption key is loaded.

**Actual behaviour**
The ap pops up a message saying: " This file is currently not supported. This doesn't seem to be a valid key file or if it is, placiibo currently doesn't support it. The selected file isn't imported, please try again and select a different key file."

**Reproducibility :** 
This issue happens every time I try to load any encryption key.

**iOS version**:
13.5.1
**iOS device**: 
iPhone XR.
**Jailbroken**: 
Not jailbroken.
**If jailbroken, can you reproduce the issue when you remove the jailbreak?**:
Do not apply.
**How did you remove the jailbreak?**:
Do not apply.

**placiibo version + build**: 
Version 0.2.0 (100)

**Screenshots**
![IMG_0270](https://user-images.githubusercontent.com/67750536/86379778-a1c34500-bc61-11ea-8317-479863af019b.PNG)
![IMG_0269](https://user-images.githubusercontent.com/67750536/86379792-a7b92600-bc61-11ea-9501-635668d6e45f.PNG)

**Screen recording**
https://gfycat.com/bravebowediriomotecat

**Relevant files**
[Archive.zip](https://github.com/placiibo/placiibo-bugs/files/4865325/Archive.zip)

**Relevant log files**
do not apply

**NFC Tag**
do not apply

**Additional context**
do not apply

**Comment by placiibo** [comment]
Thank you for filing a bug report. However based on the screenrecording and the screenshots this looks like it's behaving like intended. 
None of the shown files seem to be an encryption key, rather those should be loading into the other screen. 
Please try again with an encryption key and see if that resolves the issue.

**Comment by placiibo** [comment]
We appreciate your feedback, however, due to lack of response we have closed this report. If you are still experiencing this issue, please open a new report.

Thank you for your feedback.
