### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by suisuisame** [placiibo/placiibo-bugs#34]
**Try to describe your suggestion succinctly in the form of a user story**
As a <type of user >, I want <some goal> so that <some reason>

Ex. As a user, I want to be able to import multiple files at once so that I can save time when importing files

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by placiibo** [comment]
This seems to be an empty feature request. Please try again by filing a new one.
