### ISSUE TITLE
[Feature] Top banner text sometimes hard to read.

### ISSUE THREAD

**Issue by Lololini** [placiibo/placiibo-bugs#35]
**Try to describe your suggestion succinctly in the form of a user story**
As a user, I would like different text color options so that certain features are easier to see.

**Is your feature request related to a problem? Please describe.**
I've noticed the past couple times using this that when adding new .bin files the plus sign feels hidden. I love the colors, but they feel like they clash too much that it is harder to see everything in the top pink banner.

**Describe the solution you'd like**
I would love to see an option where we could have different text colors that could either be permanent or changeable like the light/dark option.

**Describe alternatives you've considered**
I also feel like making the cyan-colored text larger or bolder may help to see it a bit clearer. I also think it could look cool if the gradient used on the front page and for "pro" would be the banner color with white text it could also be easier to see.

**Comment by placiibo** [comment]
Thanks for the feedback. Definitely something that will be taken into consideration. Fine tuning the UI and giving some options has been in the back of my mind for a while, but it’s been something on the ‘nice to have’ list for after I’ve gotten a solid 1.0 function wise.
