### ISSUE TITLE
[Feature] Alphabetical / Numerical sorting!

### ISSUE THREAD

**Issue by meikob** [placiibo/placiibo-bugs#37]
Hello!  I am not very great at explaining, but I will to my best ability and hope you will understand.

I believe it would be nice if the names for our list of .bins were alphabetically/numerically ordered.  (A’s, B’s, C’s... OR- since I use the Amiibo # for my Animal Crossing Amiibos- #001, #002)
It’s not entirely needed, but will be handy for the future just to have everything in order like so.

Thank you so much for listening to my idea!

**Comment by placiibo** [comment]
Thank you for your feedback! 

I think it's a great idea to order the list in a certain way or even add a search functionality. I don't expect this to make it in a version soon, but after v1.0 I'll certainly take a look at implementing this. 

I've put it on my internal to-do list, thanks again for your feedback.
