### ISSUE TITLE
[BUG] Restoring purchases shows success even if there's no actual purchase to restore

### ISSUE THREAD

**Issue by HQuest** [placiibo/placiibo-bugs#38]
First and foremost, good job on making it to the App Store.

Downloaded the app from the AppStore and while reading the notes, I noticed I was now limited to 2 slots. Which is fine. Went browsing the app around and got to the tip jar page, where I tapped “Restore” and boom, “Thank you for your support. You have successfully unlocked placiibo+”. I thought “oh, that’s nice of him to get beta testers access to the full app”.

Well, my luck ended shortly. While I still had 50+ items on my library from the TestFlight days, I added two more and was met with the “you are allowed two items on your library” while adding a third one (while still maintaining my previous 50+ from the beta).

So yeah, somehow your “restore” button is not properly working (or loading the wrong panel if the restore doesn’t have anything to do). Hope others don’t find this out and go mess you up by “misleading them”.

**Comment by placiibo** [comment]
Thanks for your feedback. I still have some testing to do but it seems indeed that in certain circumstances the Restore option might wrongfully return a success message. 

In general it's advised to do a clean install if you had a TestFlight version before installing the version from the AppStore. That way the old data of the TestFlight version can't cause any issues. 

As for the remainder of your concerns; I doubt anyone reasonable will feel mislead when they tried to **restore** something that wasn't there to begin with ;)

**Comment by HQuest** [comment]
I too am never concerned about the reasonable ones. But you know how this can go downhill pretty quick with the unreasonable ones - and there are much more of them lately, trust me.

**Comment by placiibo** [comment]
The issue should be resolved in the next update 1.0.2, please confirm when the update is available and reopen the bug report if the issue still persists.
