### ISSUE TITLE
[Feature] Read functionality

### ISSUE THREAD

**Issue by ck9393** [placiibo/placiibo-bugs#39]
As a placiibo+ user , I want to be able to read our Amiiboo so that I can confirm our Amiibo are wrote correctly, or i can double confirm the Amiibo before i label it. 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when wrote Amiibo on my hand need to verify by Switch, if i can read by placiibo+ that would be more convenience. 

**Describe the solution you'd like**
I want placiibo+ not only can write to tag, but also can read from tag. 

**Describe alternatives you've considered**

**Additional context**

**Comment by placiibo** [comment]
Thank you for your feedback @ck9393 

Certainly an interessting suggestion and something we're actively looking at for a future update.
