### ISSUE TITLE
[Feature] Read NFC Data

### ISSUE THREAD

**Issue by dpearson2699** [placiibo/placiibo-bugs#41]
**Try to describe your suggestion succinctly in the form of a user story**
As a placiibo+ user, I want to be able to read a nfc card and see the data so that I can tell if it has been written to and have the opportunity to copy the nfc data and rewrite it to another tag/card.

**Is your feature request related to a problem? Please describe.** 
No

**Describe the solution you'd like**
I’d like to have a tab at the bottom of the app where the option to write to an nfc card is that says “Read,” where you can read an nfc card.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by placiibo** [comment]
Thank you for your feedback suggestion. This function is currently planned to be added in a future release.
