### ISSUE TITLE
[Feature] delete bin from main screen

### ISSUE THREAD

**Issue by ObiGKenobi** [placiibo/placiibo-bugs#5]
I'd like to be able to delete a bin after it's been written to tag, preferably by swiping on the file and selecting an option to delete it.

**Comment by placiibo** [comment]
Please fill out the Feature request template to submit a Feature request.

**Comment by placiibo** [comment]
Closed due to lack of follow up/lack of relevance for current version. Current version has a delete option that might satisfy this request.
