### ISSUE TITLE
[BUG] ntag215 should be NTAG215

### ISSUE THREAD

**Issue by EricEttes** [placiibo/placiibo-bugs#9]
**Describe the bug**
Not really a bug, more of an improvement. When the dialog opens before scanning, it asks for an ntag215. Should be NTAG215 :-)
**iOS version**:
13.4
**iOS device**: 
iPhone 11 Pro Max
**Jailbroken**: 
No
**placiibo version + build**: 
0.1.0 (12.1.1)

**Comment by placiibo** [comment]
Throwing easy ones my way, I appreciate it ;)
